### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by benatespina** [neronmoon/scriptsdev#1]
This composer plugin is very useful and works well, but we need a stable version to manage this package properly in composer

Can you publish a release please?

**Comment by neronmoon** [comment]
Sure.

**Comment by neronmoon** [comment]
Done
https://github.com/neronmoon/scriptsdev/releases/tag/v0.0.1

**Comment by benatespina** [comment]
Sorry but the best practices of SEMVER says that the first version of a package should be start in v0.1.0, because it does not have any sense start releases with a bug fix.

By the way, can you synchronize the git tags with Packagist? I'm trying to download your package via composer and packagist does not recognized the new version yet.

**Comment by neronmoon** [comment]
Ohh, ok. I've updated packagist's tags. Check pls

**Comment by benatespina** [comment]
@neronmoon Works like a charm!

**Comment by neronmoon** [comment]
Glad to hear it!
