### ISSUE TITLE
Feature request: moving the scripts-dev section into extra

### ISSUE THREAD

**Issue by TangRufus** [neronmoon/scriptsdev#2]
Please consider moving the ``scripts-dev`` section into [``extra``](https://getcomposer.org/doc/04-schema.md#extra) to avoid ``$ composer validate`` complaining it is ``not defined and the definition does not allow additional properties.``

``` bash
$ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
The property scripts-dev is not defined and the definition does not allow additional properties
```

Besides, phpstorm also flags the ``scripts-dev`` section as an error.

**Comment by neronmoon** [comment]
Done in v0.1.1
