### ISSUE TITLE
composer install call in composer script

### ISSUE THREAD

**Issue by DILL44** [neronmoon/scriptsdev#4]

**Comment by DILL44** [comment]
thank you for this useful plugin.
I have a problem when I use it in a composer script:
when I run `composer install` my script 
```
    "extra": {
        "scripts-dev": {
            "post-install-cmd": [
                        ...
            ]
        }
    },
```
my script is running but when I call `composer install` in a custom composer script:

```
    "scripts": {
        "all-in-one": [
            "composer install",
                        ...
        ]
    }
```
"post-install-cmd" in "scripts-dev" isn't running.
do you know why?

**Comment by neronmoon** [comment]
Have you tried 
```
    "scripts": {
        "all-in-one": [
            "@composer install",
                        ...
        ]
    }
```

**Comment by DILL44** [comment]
Sorry, I didn't commit my composer.lock so `post-install-cmd` didn't work in extra scripts-dev or in scripts.
I test with composer.lock and it's work.

**Comment by neronmoon** [comment]
Cool!
