### ISSUE TITLE
Packagist is not updated

### ISSUE THREAD

**Issue by sweoggy** [neronmoon/scriptsdev#6]
Packagist is out of date, dev-master is not up to date and 0.1.3 is not there.

https://packagist.org/packages/neronmoon/scriptsdev

**Comment by bahjaat** [comment]
I'm using this in ```composer.json``` now:

```"neronmoon/scriptsdev": "dev-master#4286d2009e9918ce7874a61c43640b1f1eae63d4"```

Waiting for tag to be fixed.

**Comment by neronmoon** [comment]
Sorry! Packagist has been updated now. Please check it out
