### ISSUE TITLE
[Question] short syntax for scrtiptdev commands

### ISSUE THREAD

**Issue by hanovruslan** [neronmoon/scriptsdev#7]
Hi! Is it possible to add short syntax support for composer scriptdev commands?
For now it looks like this
```
composer --dev run-script my-script-dev-command
```
and short syntax is

```
composer --dev my-script-dev-command
```

non-dev (basically composer scripts) available just like short syntax above so it will be more usefull to add short syntax for dev scripts

honestly i dont know composer  that well to find out where this support suppose to be added. Maybe in composer plugins. If so let me know. Thanks!

**Comment by neronmoon** [comment]
Hey @hanovruslan  
thanks for pointing that out. I've just published a new version with support of short syntax, so please enjoy!
